version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_DATABASE=gorm
      # - MYSQL_USER=gorm
      # - MYSQL_PASSWORD=gorm
      # - MYSQL_RANDOM_ROOT_PASSWORD="yes"