// Code generated by Kitex v0.9.0. DO NOT EDIT.

package echoservice

import (
	server "github.com/cloudwego/kitex/server"
	pdapi "github.com/zemochen/go-demo/gomall/demo/demo_proto/kitex_gen/pdapi"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler pdapi.EchoService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
